# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        #kaggle: 1
        #resnet: 1
        anomaly: 1
        recommend: 3
        graph: 2
        bandit: 1
        facebook: 1
        word2vec: 1
        item2vec: 1
        google: 1
        twitter: 1
        tiktok: 1
        xai: 1

# 通知の閾値
score_threshold: 3
